// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { getRequest } from '@tanstack/react-start/server'
import { createClient } from '@supabase/supabase-js'
import type { Database } from './types'

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

let loggedDevMockWarning = false;

export const requireSupabaseAuth = createMiddleware({ type: 'function' }).server(
  async ({ next }) => {
    const SUPABASE_URL = process.env.SUPABASE_URL || process.env.VITE_SUPABASE_URL;
    const SUPABASE_PUBLISHABLE_KEY = process.env.SUPABASE_PUBLISHABLE_KEY || process.env.VITE_SUPABASE_PUBLISHABLE_KEY;
    const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      throw new Error('Server configuration error: Missing SUPABASE_URL or SUPABASE_PUBLISHABLE_KEY environment variables');
    }

    const request = getRequest();
    if (!request?.headers) {
      throw new Error('Unauthorized: No request headers available');
    }

    const authHeader = request.headers.get('authorization');
    const hasBearerToken =
      authHeader &&
      authHeader.startsWith('Bearer ') &&
      authHeader !== 'Bearer undefined' &&
      authHeader !== 'Bearer null' &&
      authHeader !== 'Bearer';

    const isDev = process.env.NODE_ENV !== 'production';
    const isDevMockAuthEnabled = isDev && process.env.ENABLE_DEV_MOCK_AUTH === 'true';

    // -------------------------------------------------------------
    // 1. Unauthenticated request handling (no Bearer token)
    // -------------------------------------------------------------
    if (!hasBearerToken) {
      if (isDevMockAuthEnabled) {
        if (!loggedDevMockWarning) {
          console.warn(
            '[Supabase Auth] [DEV MODE ONLY] No bearer token provided. Operating with dev mock user session because ENABLE_DEV_MOCK_AUTH=true.'
          );
          loggedDevMockWarning = true;
        }

        const devKey = SUPABASE_SERVICE_ROLE_KEY || SUPABASE_PUBLISHABLE_KEY;
        const supabase = createClient<Database>(SUPABASE_URL, devKey, {
          global: {
            fetch: createSupabaseFetch(devKey),
            headers: devKey === SUPABASE_SERVICE_ROLE_KEY ? { 'x-supabase-role': 'service_role' } : {},
          },
          auth: {
            storage: undefined,
            persistSession: false,
            autoRefreshToken: false,
          },
        });

        const mockUserId = process.env.DEV_MOCK_USER_ID || '623eb6d8-49c5-4f69-8abe-779d3b71811e';
        return next({
          context: {
            supabase,
            userId: mockUserId,
            claims: { sub: mockUserId } as any,
          },
        });
      }

      // Production or whenever ENABLE_DEV_MOCK_AUTH is false/missing: strict 401
      throw new Error('Unauthorized: Missing authorization header');
    }

    // -------------------------------------------------------------
    // 2. Authenticated token verification
    // -------------------------------------------------------------
    const token = authHeader.replace('Bearer ', '').trim();
    if (!token || token.split('.').length !== 3) {
      throw new Error('Unauthorized: Invalid bearer token structure');
    }

    const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      global: {
        fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
        headers: {
          Authorization: `Bearer ${token}`,
        },
      },
      auth: {
        storage: undefined,
        persistSession: false,
        autoRefreshToken: false,
      },
    });

    const { data, error } = await supabase.auth.getClaims(token);
    if (error || !data?.claims || !data.claims.sub) {
      throw new Error('Unauthorized: Invalid or expired access token');
    }

    return next({
      context: {
        supabase,
        userId: data.claims.sub,
        claims: data.claims,
      },
    });
  }
);
